name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v7
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Install Dependencies
      run: pnpm install
      
    - name: Run Validation Checks
      run: pnpm validate
      
    - name: Run Tests
      run: pnpm test
